namespace: grnet
name: nextcloud
version: 0.1.0-dev0
readme: README.md
authors:
- Antonis Christofides <antonis@admin.grnet.gr>
description: Ansible roles for installing Nextcloud on Debian/Ubuntu servers
license:
- GPL-3.0-or-later
tags: []
dependencies:
  git+https://github.com/aptiko/aptiko.general.git: master
repository: https://github.com/grnet/grnet.nextcloud
documentation: https://grnetnextcloud.readthedocs.com
homepage: https://github.com/grnet/grnet.nextcloud
issues: https://github.com/grnet/grnet.nextcloud/issues/
build_ignore: []

